name: GitHub Pages

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '*/5 * * * *' # update every 5 minutes

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install

      - name: Update cases
        run: node build.js

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./
          enable_jekyll: true
